/** Copy do painel de admin. Português direto; quem lê é a equipe, não a mãe. */
export const adminCopy = {
  titulo: "Painel do Ninho",
  nav: {
    rotulo: "Seções do painel",
    visao: "Visão geral",
    usuarias: "Usuárias",
    conteudo: "Conteúdo",
    faq: "FAQ de comidas",
    voz: "Voz",
    sistema: "Sistema",
    voltarApp: "Abrir o app",
    sair: "Sair",
  },
  demo: {
    faixa: "Dados de demonstração. Ligue o Supabase para ver os números de verdade.",
    comoLigar: "Como ligar",
  },
  entrar: {
    titulo: "Entrar no painel",
    apoio: "A gente manda um link para o seu e-mail. Só e-mails da lista de admins entram.",
    rotuloEmail: "E-mail",
    enviar: "Enviar link",
    enviado: "Link enviado. Abra o e-mail neste mesmo navegador.",
    erro: "Não deu para enviar. Confira o e-mail e tente de novo.",
    semPermissao: (email: string) => `${email} não está na lista de admins. Peça para adicionar em supabase/seed.sql ou na tabela admins.`,
    trocarConta: "Entrar com outro e-mail",
  },
  estados: {
    carregando: "Carregando…",
    erro: "Não deu para carregar. Tente de novo.",
    tentar: "Tentar de novo",
    vazio: "Nada por aqui ainda.",
    tabela: "Ver como tabela",
    grafico: "Ver como gráfico",
    atualizado: (quando: string) => `Atualizado ${quando}`,
    atualizar: "Atualizar",
  },
  periodo: {
    rotulo: "Período",
    d7: "7 dias",
    d30: "30 dias",
    d90: "90 dias",
  },
  visao: {
    titulo: "Visão geral",
    familias: "Famílias",
    familiasApoio: "desde o começo",
    novas7d: "Novas em 7 dias",
    ativas7d: "Ativas em 7 dias",
    ativas1d: "Ativas hoje",
    pagantes: "Com plano",
    pagantesApoio: (trial: number, cortesia: number) => `${trial} em trial · ${cortesia} em cortesia`,
    modo: "Gestação × bebê",
    modoApoio: "famílias por modo",
    serieTitulo: "Famílias por dia",
    serieApoio: "novas e ativas, por dia",
    novas: "Novas",
    ativas: "Ativas",
    registros: "Registros",
    leituras: "Leituras",
    usoTitulo: "Uso por dia",
    usoApoio: "registros do bebê e stories lidas",
    tiposTitulo: "Registros por tipo",
    tiposApoio: "últimos 30 dias",
    sintomasTitulo: "Sintomas mais marcados",
    sintomasApoio: "últimos 30 dias, só a contagem",
    funilTitulo: "Da primeira abertura ao cadastro",
    funilApoio: "perfis criados → onboarding concluído → e-mail guardado",
    perfis: "Perfis",
    onboarding: "Onboarding concluído",
    comEmail: "Com e-mail",
    vsAnterior: "vs. período anterior",
  },
  usuarias: {
    titulo: "Usuárias",
    apoio: "Só agregados e ids. Nome, sintoma e nota nunca chegam aqui.",
    semanasTitulo: "Gestantes por semana",
    semanasApoio: "em que semana cada gestante está hoje",
    mesesTitulo: "Bebês por mês de vida",
    mesesApoio: "idade dos bebês cadastrados",
    papeisTitulo: "Quem usa",
    papeisApoio: "membros por papel na família",
    planosTitulo: "Planos",
    planosApoio: "famílias por plano",
    origensTitulo: "Como registram",
    origensApoio: "origem dos registros nos últimos 30 dias",
    listaTitulo: "Famílias",
    listaApoio: "as mais ativas primeiro",
    colunas: { id: "Id", modo: "Modo", momento: "Momento", membros: "Membros", plano: "Plano", registros: "Registros", criada: "Criada", ultimo: "Último acesso" },
    momento: (semana: number | null, mes: number | null) => (mes !== null ? `mês ${mes}` : semana !== null ? `semana ${semana}` : "–"),
    modoNome: { gestacao: "Gestação", bebe: "Bebê" } as Record<string, string>,
    papelNome: { mae: "Mãe", parceiro: "Parceiro(a)", avo: "Avó/avô", cuidador: "Cuidador(a)" } as Record<string, string>,
    planoNome: { free: "Grátis", trial: "Trial", ativo: "Ativo", expirado: "Expirado" } as Record<string, string>,
    origemNome: { manual: "Na mão", voz: "Por voz", timer: "Timer" } as Record<string, string>,
    tipoNome: { sono: "Sono", mamada: "Mamada", fralda: "Fralda", banho: "Banho", outro: "Outro" } as Record<string, string>,
    maisFamilias: "Carregar mais",
  },
  conteudo: {
    titulo: "Conteúdo",
    apoio: "O que cada mãe vê no carrossel 'Hoje para você', por dia.",
    novo: "Novo conteúdo",
    abas: { lista: "Todos", calendario: "Por dia" },
    busca: "Buscar por título",
    filtros: { todos: "Todos", publicados: "Publicados", rascunhos: "Rascunhos", premium: "Premium" },
    colunas: { titulo: "Título", categoria: "Categoria", faixa: "Aparece em", dia: "Dia", leituras: "Leituras", guardados: "Guardados", estado: "Estado" },
    publicado: "Publicado",
    rascunho: "Rascunho",
    premium: "Premium",
    qualquerDia: "qualquer dia",
    total: (n: number, publicados: number) => `${n} conteúdos · ${publicados} publicados`,
    vazio: "Nenhum conteúdo com esse filtro.",
    calendario: {
      apoio: "Simula os 3 stories que aparecem em cada dia da semana para quem está neste momento. A story da semana vem sempre primeiro; as outras giram por dia.",
      modo: "Momento",
      gestacao: "Gestação",
      bebe: "Bebê",
      semana: "Semana",
      mes: "Mês do bebê",
      elegiveis: (n: number) => `${n} conteúdos elegíveis neste momento`,
      semStories: "Nenhum conteúdo publicado para este momento. Quem estiver aqui vê o carrossel vazio.",
      hoje: "hoje",
      doDia: "fixo neste dia",
    },
    editor: {
      novoTitulo: "Novo conteúdo",
      editarTitulo: "Editar conteúdo",
      titulo: "Título",
      slug: "Slug",
      slugAjuda: "Vira o endereço da story. Gerado do título; só mude se precisar.",
      categoria: "Categoria",
      faixaTitulo: "Quando aparece",
      faixaApoio: "Preencha semanas da gestação, meses do bebê, ou os dois.",
      semanaMin: "Da semana",
      semanaMax: "Até a semana",
      mesMin: "Do mês",
      mesMax: "Até o mês",
      diaDaSemana: "Dia fixo da semana",
      diaAjuda: "Opcional. Nesse dia ele entra antes dos outros.",
      qualquerDia: "Qualquer dia",
      minutos: "Minutos de leitura",
      premium: "Premium",
      premiumAjuda: "Sem plano, a mãe vê só o primeiro card.",
      publicado: "Publicado",
      publicadoAjuda: "Rascunho não aparece para ninguém.",
      corpo: "Cards",
      corpoAjuda: "Um card por bloco, separados por uma linha com ---. Negrito com **texto**, itálico com _texto_, listas com -.",
      inserirFrase: "Inserir frase de encaminhamento",
      preview: "Como a mãe vê",
      cardDe: (i: number, n: number) => `${i} de ${n}`,
      problemas: "Antes de salvar",
      salvar: "Salvar",
      salvarPublicar: "Salvar e publicar",
      salvo: "Salvo",
      publicadoToast: "Publicado",
      despublicar: "Despublicar",
      apagar: "Apagar rascunho",
      apagarConfirma: "Apagar este rascunho? Não dá para desfazer.",
      apagado: "Rascunho apagado",
      erro: "Não deu para salvar. Tente de novo.",
      naoEncontrado: "Esse conteúdo não existe.",
      voltar: "Voltar para a lista",
      semanaAvisos: "Story da semana: uma semana só, nunca premium.",
    },
    categoriaNome: {
      semana: "Semana",
      corpo: "Seu corpo",
      bebe: "Bebê",
      parto: "Parto",
      pos_parto: "Pós-parto",
      sono: "Sono",
      amamentacao: "Amamentação",
    } as Record<string, string>,
  },
  voz: {
    titulo: "Voz",
    apoio: "Quanto a interpretação acerta. A transcrição fica só aqui.",
    total: "Interpretações",
    totalApoio: "desde o começo",
    aceitas: "Aceitas de primeira",
    corrigidas: "Corrigidas",
    naoEntendidas: "Não entendidas",
    confianca: "Confiança média",
    latencia: "Tempo mediano",
    recentesTitulo: "Últimas interpretações",
    recentesApoio: "o que a pessoa disse e o que o modelo entendeu",
    colunas: { quando: "Quando", transcricao: "Transcrição", resultado: "Resultado", confianca: "Confiança", estado: "Estado", tempo: "Tempo" },
    estado: { aceita: "Aceita", corrigida: "Corrigida", recusada: "Recusada", pendente: "Sem resposta" },
    vazio: "Nenhuma interpretação registrada ainda. Elas aparecem quando a Edge Function estiver no ar.",
    resumoResposta: (n: number, tipos: string) => (n === 0 ? "nada entendido" : `${n} ${n === 1 ? "registro" : "registros"}: ${tipos}`),
  },
  sistema: {
    titulo: "Sistema",
    apoio: "O que está ligado e o que falta.",
    supabase: "Supabase",
    supabaseOk: "Conectado",
    supabaseOff: "Sem variáveis de ambiente. O app roda 100 % local e este painel mostra dados de demonstração.",
    edge: "Interpretação por voz (Edge Function)",
    edgeOk: "Configurada",
    edgeOff: "Sem servidor; o parser local assume.",
    analytics: "Analytics (GA4)",
    analyticsOk: "Ligado",
    analyticsOff: "NEXT_PUBLIC_GA_ID não definido.",
    banco: "Banco de conteúdo",
    bancoBundle: (n: number) => `${n} conteúdos no bundle do app`,
    bancoServidor: (n: number) => `${n} conteúdos no servidor`,
    bancoAjuda: "O bundle sai do repositório (content/*.md). O que você edita aqui vai para o servidor e o app mescla os dois.",
    admin: "Sua conta",
    adminApoio: (email: string) => `Entrou como ${email}`,
    versao: "Versão",
    passos: "Para ligar o Supabase",
    passosLista: [
      "Crie o projeto em supabase.com e rode `supabase link` e `supabase db push`.",
      "Em Authentication, ligue Anonymous sign-ins e o provedor de e-mail.",
      "Na Vercel, defina NEXT_PUBLIC_SUPABASE_URL e NEXT_PUBLIC_SUPABASE_ANON_KEY e faça redeploy.",
      "Rode `pnpm conteudo:sync` para subir o banco de conteúdo e o catálogo de sintomas.",
    ],
  },
} as const;
