/** Copy da funcionalidade 11 · Adaptação por trimestre (home, artigos, virada). Tom "a gente", frases curtas. */
const plural = (n: number, um: string, varios: string) => (n === 1 ? `1 ${um}` : `${n} ${varios}`);

export const artigosCopy = {
  titulo: "Artigos",
  paraEstaSemana: "Para esta semana",
  todosLidos: "Você leu tudo desta semana. Que tal a biblioteca?",
  biblioteca: "Biblioteca",
  aba: (t: number) => `${t}º tri`,
  abaRotulo: (t: number) => `${t}º trimestre`,
  busca: "Buscar artigo",
  buscaPlaceholder: "Ex.: enjoo, mala, sono",
  resultados: (n: number) => (n === 1 ? "1 artigo" : `${n} artigos`),
  nenhum: "Nenhum artigo com esse texto. Tente outra palavra.",
  favoritos: "Meus favoritos",
  semArtigos: "Ainda não tem artigo publicado aqui. Volte em breve.",
  minutos: (m: number) => `${m} min de leitura`,
  semanas: (de: number, ate: number) => (de === ate ? `Semana ${de}` : `Semanas ${de} a ${ate}`),
  lido: "Lido",
  rascunho: "Rascunho: aguarda revisão profissional",
  rascunhoRodape: "Este texto ainda não passou pela revisão de um profissional de saúde.",
  revisado: (quem: string, quando: string) => `Revisado por ${quem} em ${quando}.`,
  aviso: "Informação geral. Em caso de dúvida, fale com sua equipe de saúde.",
  favoritar: "Favoritar",
  desfavoritar: "Tirar dos favoritos",
  favoritado: "Nos seus favoritos ✓",
  naoEncontrado: "Esse artigo não está disponível agora.",
  voltar: "Artigos",
  premium: "Este artigo faz parte do plano Completo. Aqui vai o resumo:",
  premiumCta: "Conhecer o Completo",

  home: {
    resumo: "Resumo da semana",
    feito: "Feito",
    exames: { titulo: "Exames a marcar", pendente: (n: number) => `${plural(n, "exame", "exames")} com a janela aberta`, normal: "Nada para marcar agora", vazio: "Veja os exames do pré-natal" },
    medicamentos: {
      titulo: "Medicamentos de hoje",
      pendente: (tomadas: number, total: number) => `${tomadas} de ${total} doses tomadas`,
      feito: "Todas as doses de hoje tomadas",
      normal: "Nenhuma dose marcada para hoje",
      vazio: "Cadastre um lembrete de remédio ou vitamina",
    },
    marco: { titulo: "Marco do diário", vazio: "Escreva a primeira página do diário", normal: "Seu diário está em dia" },
    foto: { titulo: "Foto da semana", pendente: (s: number) => `Tire a foto da semana ${s}`, feito: (s: number) => `Foto da semana ${s} guardada` },
    plano: { titulo: "Plano de parto", progresso: (f: number) => `${f} de 5 etapas`, feito: "Plano de parto pronto", comecar: "Maternidade, acompanhante e o que você deseja" },
    mala: { titulo: "Mala e enxoval", progresso: (f: number, t: number) => `${f} de ${t} itens prontos`, feito: "Tudo pronto", comecar: "Monte a mala com a lista pronta" },
    artigo: { titulo: "Artigo da semana", feito: "Você leu os artigos desta semana" },
    oracao: { titulo: "Oração da semana" },
    faq: { titulo: "Posso comer?", texto: "Busque um alimento e veja se pode na gravidez" },
    direitos: {
      titulo: "Seus direitos nesta fase",
      // Fatos da lei, sem interpretação: CLT art. 392 §4º, ADCT art. 10, Lei 11.108/2005 e CLT art. 392.
      texto: {
        1: "A lei garante a saída do trabalho para consultas e exames do pré-natal.",
        2: "Você tem estabilidade no emprego desde a confirmação da gravidez até 5 meses após o parto.",
        3: "Acompanhante de sua escolha no parto e licença-maternidade de 120 dias.",
      } as Record<1 | 2 | 3, string>,
    },
  },

  virada: {
    titulo: (t: 2 | 3) => (t === 2 ? "Bem-vinda ao 2º trimestre!" : "Bem-vinda ao 3º trimestre!"),
    sub: (t: 2 | 3) => (t === 2 ? "O 1º trimestre ficou para trás. Olha o que você guardou nele:" : "A reta final começou. Olha o que você guardou no 2º trimestre:"),
    numeros: "Números do trimestre",
    fotos: (n: number) => (n === 1 ? "foto da barriga" : "fotos da barriga"),
    marcos: (n: number) => (n === 1 ? "marco no diário" : "marcos no diário"),
    consultas: (n: number) => (n === 1 ? "consulta feita" : "consultas feitas"),
    oQueEsperar: "O que esperar",
    irParaHome: "Ir para a home",
    verBiblioteca: "Ver todos os artigos",
  },
} as const;
