/** Copy da funcionalidade 05 · Foto semanal da barriga. */
export const barrigaCopy = {
  titulo: "Barriga",
  semana: (n: number) => `Semana ${n}`,
  /** Selo desenhado no vídeo e na imagem compartilhada ({n} vira o número). */
  seloSemana: "Semana {n}",
  marca: "Ninho",
  vazio: (n: number) => `Tire a foto da semana ${n}`,
  vazioApoio: "Uma foto por semana, sempre do mesmo jeito. No fim, vira um vídeo.",
  antesDaSemana4: "A grade começa na semana 4.",
  tirarFoto: "Tirar a foto",
  semanaAtual: "esta semana",
  adicionarSemana: (n: number) => `Adicionar foto da semana ${n}`,
  verSemana: (n: number) => `Ver a foto da semana ${n}`,
  semanaFutura: (n: number) => `Semana ${n}, ainda não chegou`,
  timelapse: "Timelapse",
  timelapseFalta: (n: number) => (n === 1 ? "Falta 1 foto para o timelapse" : `Faltam ${n} fotos para o timelapse`),
  retomarTitulo: "Retomar as fotos?",
  retomarApoio: "Faz 3 semanas sem foto, então a gente parou de lembrar. Quer voltar?",
  retomar: "Retomar",
  retomado: "A gente volta a lembrar ✓",
  dispensar: "Agora não",
  // Escolher origem
  comoAdicionar: (n: number) => `Foto da semana ${n}`,
  camera: "Câmera",
  galeria: "Galeria",
  // Câmera
  fechar: "Fechar a câmera",
  virar: "Virar a câmera",
  grade: "Grade",
  fantasma: "Silhueta da semana anterior",
  fantasmaDa: (n: number) => `Silhueta da semana ${n}`,
  disparar: "Tirar a foto",
  semCamera: "Sem acesso à câmera aqui. Mande uma foto da galeria ou use a câmera do celular.",
  usarCameraDoCelular: "Abrir a câmera do celular",
  escolherDaGaleria: "Escolher da galeria",
  processando: "Preparando a foto…",
  erroFoto: "Não deu para usar essa foto. Tenta outra?",
  // Confirmar
  confirmarTitulo: (n: number) => `Semana ${n}`,
  legenda: "Legenda (opcional)",
  usarEsta: "Usar esta",
  refazer: "Refazer",
  substituirTitulo: (n: number) => `Substituir a foto da semana ${n}?`,
  substituirTexto: "A foto atual sai e esta entra no lugar.",
  substituir: "Substituir",
  cancelar: "Cancelar",
  salva: (n: number) => `Foto da semana ${n} guardada ✓`,
  // Foto da semana
  editarLegenda: "Editar legenda",
  salvarLegenda: "Salvar",
  legendaSalva: "Legenda salva ✓",
  substituirFoto: "Substituir",
  excluir: "Excluir",
  excluirTitulo: "Excluir esta foto?",
  excluirTexto: "A semana fica livre para outra foto. Não dá para desfazer.",
  excluida: "Foto excluída",
  compartilhar: "Compartilhar",
  salvaNoAparelho: "Imagem salva no aparelho ✓",
  carregando: "Carregando a foto…",
  semArquivo: "A foto ainda não chegou neste aparelho.",
  // Timelapse
  play: "Tocar",
  pausar: "Pausar",
  velocidade: "Velocidade",
  velocidades: { "0.2": "Rápido", "0.4": "Normal", "0.8": "Devagar" } as Record<string, string>,
  exportar: "Exportar vídeo",
  exportarFree: "Exportar vídeo (720p)",
  exportarHd: "Em 1080p, sem marca",
  exportando: "Montando o vídeo…",
  exportado: "Vídeo pronto ✓",
  exportarErro: "Não deu para montar o vídeo. Tenta de novo?",
  semExportar: "Seu navegador não exporta vídeo. Use o player do app.",
  exportarMarca: "Exportar em 720p com marca Ninho",
  minimo: "O timelapse aparece com 3 fotos ou mais.",
  // Preferências
  lembretes: "Lembrete semanal",
  lembretesApoio: "No dia da virada da semana, se ainda não tiver foto.",
} as const;
