/** Copy da home do bebê, tiles e sheets de registro (specs 09 e 10). */
export const bebeCopy = {
  tiles: {
    sono: "Sono",
    mamada: "Mamada",
    fralda: "Fralda",
    banho: "Banho",
    naoRegistrado: "ainda não registrado",
    dormindo: "Dormindo",
    mamando: "Mamando",
  },
  idade: {
    corrigida: (t: string) => `corrigida: ${t}`,
    deVida: "de vida",
  },
  dicaVoz: "Segure o microfone no + e diga “mamou 12 minutos no direito”.",
  verDia: "Ver o dia",
  verSono: "Ver o sono",
  seletorBebe: "Escolher bebê",

  sono: {
    titulo: "Sono",
    comecarAgora: "Começar agora",
    informar: "Informar início e fim",
    inicio: "Começou",
    fim: "Acordou",
    acordouAgora: "Acordou agora",
    ajustarHora: "Ajustar hora",
    encerrarAnterior: (hora: string) => `Tem um sono em andamento desde ${hora}. Encerrar ele agora e começar outro?`,
    encerrarEComecar: "Encerrar e começar",
    salvar: "Salvar",
    iniciado: "Sono começou ✓",
    registrado: "Sono registrado ✓",
    fimAntesDoInicio: "O fim precisa vir depois do início.",
  },
  mamada: {
    titulo: "Mamada",
    peito: "Peito",
    mamadeira: "Mamadeira",
    bomba: "Bomba",
    esquerdo: "Esquerdo",
    direito: "Direito",
    trocarLado: "Trocar lado",
    encerrar: "Encerrar",
    ladoE: "E",
    ladoD: "D",
    leite: "Leite materno",
    formula: "Fórmula",
    quando: "Quando",
    registrar: "Registrar",
    iniciada: (lado: string) => `Mamada no ${lado} começou ✓`,
    registrada: "Mamada registrada ✓",
    semVolume: "Digite o volume.",
  },
  fralda: {
    titulo: "Fralda",
    xixi: "Xixi",
    coco: "Cocô",
    ambos: "Os dois",
    seca: "Seca",
    quando: "Quando",
    registrada: "Fralda registrada ✓",
  },
  banho: {
    titulo: "Banho",
    agora: "Registrar agora",
    quando: "Quando",
    salvar: "Salvar",
    registrado: "Banho registrado ✓",
  },
  outro: {
    titulo: "Outro",
  },
  erro: {
    futuro: "Essa hora ainda não chegou.",
    antigo: "Só dá para registrar as últimas 24 h.",
  },
  apagar: "Apagar",
  apagado: (tipo: string) => `${tipo} apagado`,
  desfazer: "Desfazer",
  editar: "Editar",

  dia: {
    titulo: "O dia",
    vazio: "Nada registrado hoje ainda. O primeiro toque num tile já entra aqui.",
    emAndamento: "em andamento",
    por: (nome: string) => `por ${nome}`,
  },

  soneca: {
    titulo: "Próxima soneca",
    semDados: "Registre o próximo sono para eu começar a prever.",
    provavel: (ini: string, fim: string) => `Provável entre ${ini} e ${fim}`,
    linha: (vigilia: string, acordou: string) => `janela de vigília de ${vigilia} · acordou às ${acordou}`,
    agora: (fim: string) => `É agora: janela até ${fim}`,
    passou: (min: number) => `Passou da janela há ${min} min`,
    dormindo: (min: number) => `Dormindo há ${min} min`,
    baseMediana: "calibrada pelos últimos 7 dias",
    baseTabela: "referência pela idade",
    telaTitulo: "Sono",
    ultimos7: "Últimos 7 dias",
    sonecaLegenda: "sonecas",
    noiteLegenda: "noite",
    vigiliaMedia: (t: string) => `Vigília provável: ${t}`,
    aviso: "Aviso 10 min antes da janela",
    avisoApoio: "Só de dia, no máximo 6 por dia. Chega na próxima etapa, com as notificações.",
    semRegistros: "Sem sono registrado nos últimos 7 dias.",
  },
} as const;
