/** Copy da funcionalidade 08 · Calendário. */
export const calendarioCopy = {
  titulo: "Calendário",
  modo: "Ver como",
  mes: "Mês",
  agenda: "Agenda",
  hoje: "Hoje",
  mesAnterior: "Mês anterior",
  proximoMes: "Próximo mês",
  diasDaSemana: ["D", "S", "T", "Q", "Q", "S", "S"],
  diasDaSemanaLongos: ["domingo", "segunda", "terça", "quarta", "quinta", "sexta", "sábado"],
  meses: ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"],
  marcadorSemana: (s: number) => `${s}s`,
  diaRotulo: (data: string, n: number) => (n === 0 ? data : `${data}, ${n === 1 ? "1 item" : `${n} itens`}`),
  viradaRotulo: (s: number) => `começa a semana ${s}`,
  mais: (n: number) => `+${n}`,
  vazio: "Nada marcado. Que tal anotar sua próxima consulta?",
  vazioConsulta: "Marcar consulta",
  novo: "Novo evento",
  agendaVazia: "Nada nos próximos dias.",
  hojeCabecalho: (g: string | null) => (g ? `Hoje, ${g}` : "Hoje"),
  diaCabecalho: (d: string, g: string | null) => (g ? `${d} · ${g}` : d),
  diaInteiro: "dia inteiro",
  feito: "feita",
  pendente: "ainda não",
  semItens: "Nada neste dia.",
  adicionarEvento: "Adicionar evento neste dia",
  exportar: (t: string) => `Adicionar "${t}" ao meu calendário`,
  exportado: "Arquivo do calendário pronto ✓",
  abrir: (t: string) => `Abrir ${t}`,
  tipos: {
    appointment: "Consulta",
    exam: "Exame",
    custom: "Evento",
    med_day: "Medicamentos",
    belly_photo: "Foto da semana",
    edd: "DPP",
  },
  // Evento próprio (tela 4)
  editar: "Editar evento",
  tituloCampo: "Título",
  tituloErro: "Dê um nome ao evento.",
  tituloLongo: "Até 80 letras.",
  categoria: "Tipo",
  categorias: { exam: "Exame", appointment: "Consulta", course: "Curso", purchase: "Compras", other: "Outro" },
  diaInteiroCampo: "Dia inteiro",
  data: "Data",
  dataErro: "Escolha a data.",
  hora: "Hora",
  horaErro: "Escolha a hora (ou marque dia inteiro).",
  observacao: "Observação (opcional)",
  lembrete: "Lembrete",
  lembretes: { nenhum: "Nenhum", "0": "Na hora", "60": "1 hora antes", "1440": "1 dia antes, às 9h" },
  visivelParceiro: "Mostrar para meu parceiro",
  visivelParceiroApoio: "Ele vê a data e o título.",
  salvar: "Salvar",
  salvo: "Evento salvo ✓",
  excluir: "Excluir evento",
  excluirTitulo: "Excluir este evento?",
  excluirTexto: "Ele sai do calendário e o lembrete é cancelado.",
  excluido: "Evento excluído",
  cancelar: "Cancelar",
  naoEditavel: "Este item vem de outra parte do app. Abra para mudar.",
  // Ajustes do calendário (tela 5)
  ajustes: "Ajustes do calendário",
  feedTitulo: "Assinar no Google ou Apple",
  feedApoio: "Gere um link e assine no Google Agenda ou no Calendário do iPhone. Entram consultas, exames marcados, seus eventos e a DPP. Medicamentos, fotos e observações ficam de fora.",
  feedAviso: "Qualquer pessoa com este link vê esses compromissos.",
  gerarLink: "Gerar link",
  copiarLink: "Copiar link",
  copiado: "Link copiado ✓",
  revogar: "Revogar e gerar outro",
  revogarTitulo: "Revogar o link?",
  revogarTexto: "Quem assinou deixa de receber atualizações. Um link novo é gerado.",
  revogado: "Link revogado. Este é o novo ✓",
  comoAssinar: "No Google Agenda: Outras agendas → Do URL. No iPhone: Ajustes → Calendário → Contas → Adicionar calendário assinado.",
  precisaServidor: "O link de assinatura precisa de internet e de uma conta conectada.",
  erro: "Não deu certo agora. Tenta de novo?",
} as const;
