/** Copy da funcionalidade 14 · Cartas para o bebê. Frases curtas, tom "a gente". */
export const cartasCopy = {
  titulo: "Cartas",
  para: (nome: string) => `Para ${nome}`,
  bebe: "o bebê",
  vazio: (nome: string) => `Escreva a primeira carta para ${nome}`,
  vazioApoio: "Ela fica guardada e lacrada até o dia que você escolher.",
  escrever: "Escrever carta",
  secoes: { draft: "Rascunhos", sealed: "Lacradas", opened: "Abertas" },
  abreEm: (data: string) => `Abre em ${data}`,
  abriuEm: (data: string) => `Aberta em ${data}`,
  semData: "Sem data de abertura",
  exportar: "Exportar cartas (ZIP)",
  exportarApoio: "Rascunhos e abertas, com texto, áudio e foto. As lacradas ficam de fora.",
  exportado: (n: number) => (n === 1 ? "1 carta exportada ✓" : `${n} cartas exportadas ✓`),
  nadaParaExportar: "Ainda não há rascunho nem carta aberta para exportar.",
  emailAnual: "Lembrete anual por e-mail",
  emailAnualApoio: "No aniversário do nascimento, um e-mail avisa que as cartas lacradas estão guardadas.",

  editor: {
    novo: "Nova carta",
    editar: "Rascunho",
    titulo: "Título",
    tituloPlaceholder: "Ex.: Para o seu primeiro aniversário",
    texto: "Carta",
    textoPlaceholder: "Escreva com calma. Dá para voltar depois.",
    regra: "Quando abrir",
    regras: {
      first_birthday: "1º aniversário",
      age_5: "5 anos",
      age_10: "10 anos",
      age_15: "15 anos",
      age_18: "18 anos",
      custom: "Escolher a data",
    },
    dataPropria: "Data de abertura",
    dataPropriaApoio: (min: string, max: string) => `De ${min} a ${max}.`,
    abririaEm: (data: string) => `Abriria em ${data}.`,
    abririaEmDpp: "Pela data prevista do parto; quando o nascimento for registrado, a data é recalculada.",
    email: "Entregar também por e-mail (opcional)",
    emailApoio: "No dia, quem receber ganha um link de leitura. Dá para preencher depois.",
    audio: "Gravar áudio",
    audioApoio: "Até 5 minutos.",
    parar: "Parar",
    removerAudio: "Remover áudio",
    foto: "Escolher foto",
    removerFoto: "Remover foto",
    premium: "Áudio e foto são do Completo.",
    salvar: "Salvar rascunho",
    salvo: "Rascunho salvo ✓",
    salvoOffline: "Salvo no aparelho. Sobe quando a internet voltar.",
    lacrar: "Lacrar",
    excluir: "Excluir carta",
    erros: {
      titulo: "Dê um título (até 80 caracteres).",
      texto_longo: "A carta passou de 5.000 caracteres.",
      email: "Confira o e-mail.",
      conteudo: "Escreva o texto ou grave um áudio.",
      regra: "Escolha quando abrir.",
      data: "Escolha uma data dentro do prazo.",
      carta_lacrada: "Esta carta já foi lacrada.",
    },
  },

  lacre: {
    titulo: "Lacrar a carta?",
    resumo: (data: string) => `Esta carta só poderá ser lida em ${data}.`,
    aviso: "Depois de lacrada, nem você lê o conteúdo até a data. Fica só o título e o dia de abrir.",
    confirmar: "Lacrar",
    cancelar: "Voltar",
    pronto: "Carta lacrada ✓",
    erros: {
      sem_servidor: "Isso precisa de conta com internet: é no servidor que a carta fica protegida.",
      sem_rede: "Isso precisa de internet.",
      pendente: "Ainda enviando a carta. Tente de novo em instantes.",
      sem_conteudo: "Escreva o texto ou grave um áudio antes de lacrar.",
      data_invalida: "A data escolhida está fora do prazo.",
      sem_referencia: "Falta a data prevista do parto para calcular quando abrir.",
      desconhecido: "Não deu certo. Tente de novo.",
    },
  },

  lacrada: {
    apoio: "Lacrada. O conteúdo aparece no dia de abrir.",
    deslacrar: "Abrir antes da hora",
    confirmar1: "Quer mesmo abrir antes da hora?",
    confirmar1Texto: "A carta volta a ser rascunho. Para guardar de novo, será preciso lacrar outra vez.",
    confirmar2: "Tem certeza?",
    confirmar2Texto: "A surpresa da data escolhida se perde.",
    sim: "Sim, abrir",
    simMesmo: "Abrir agora",
    nao: "Manter lacrada",
    deslacrada: "Carta de volta aos rascunhos",
  },

  aberta: {
    entregar: (nome: string) => `Entregar a ${nome}`,
    entregarApoio: "Um link de leitura que vale 30 dias. Mande pelo app que quiser.",
    gerarLink: "Gerar link de leitura",
    linkPronto: "Link pronto ✓",
    copiado: "Link copiado ✓",
    revogar: "Revogar link",
    revogado: "Link revogado. Quem tinha não lê mais.",
    exportar: "Exportar esta carta",
    textoCompartilhar: (titulo: string) => `Uma carta para você: ${titulo}`,
  },

  excluir: {
    titulo: "Excluir a carta?",
    texto: "É definitivo: o texto, o áudio e a foto são apagados. Não dá para desfazer.",
    confirmar: "Excluir",
    cancelar: "Cancelar",
    pronto: "Carta excluída",
  },

  publica: {
    carregando: "Abrindo a carta…",
    naoEncontrada: "Este link não abre mais. Pode ter vencido ou sido revogado.",
    erro: "Não deu para abrir agora. Tente de novo mais tarde.",
    rodape: "Guardada com carinho no Ninho.",
    audio: "Áudio da carta",
    foto: "Foto da carta",
  },
} as const;
