/** Copy da funcionalidade 04 · Cronograma de consultas. */
export const consultasCopy = {
  titulo: "Consultas",
  proxima: "Próxima",
  futuras: "Depois",
  passadas: "Anteriores",
  vazio: "Cadastre sua próxima consulta",
  vazioApoio: "Dá para anotar perguntas mesmo sem data marcada.",
  nova: "Nova consulta",
  editar: "Editar consulta",
  data: "Data",
  hora: "Hora",
  tipo: "Tipo",
  profissional: "Profissional (opcional)",
  papel: "Quem atende (opcional)",
  local: "Local (opcional)",
  salvar: "Salvar",
  salva: "Consulta salva ✓",
  salvaPassada: "Consulta registrada como feita ✓",
  erroData: "Escolha data e hora.",
  cancelar: "Cancelar consulta",
  cancelada: "Consulta cancelada",
  excluir: "Excluir",
  excluirConfirma: "Excluir esta consulta? As medidas dela somem e as perguntas voltam para a pauta.",
  excluida: "Consulta excluída",
  voltar: "Voltar",
  status: { scheduled: "marcada", done: "feita", cancelled: "cancelada" },
  // Pauta
  pauta: "Pauta",
  pautaApoio: "O que você quer perguntar. Vai para a próxima consulta.",
  pautaVazia: "Nenhuma pergunta ainda.",
  perguntasNaPauta: (n: number) => (n === 1 ? "1 pergunta na pauta" : `${n} perguntas na pauta`),
  novaPergunta: "Nova pergunta",
  perguntaPlaceholder: "O que você quer perguntar?",
  perguntaErro: "Escreva de 3 a 280 letras.",
  adicionarPergunta: "Anotar",
  ditar: "Ditar a pergunta",
  pararDitado: "Parar de ditar",
  perguntaSalva: "Pergunta anotada ✓",
  apagarPergunta: (t: string) => `Apagar “${t}”`,
  perguntaApagada: "Pergunta apagada",
  porQuem: (nome: string) => `anotada por ${nome}`,
  semVoz: "Sem ditado neste navegador. Escreva a pergunta.",
  // Concluir
  concluir: "Concluir consulta",
  concluida: "Consulta concluída ✓",
  passo: (n: number) => `Passo ${n} de 3`,
  pular: "Pular",
  continuar: "Continuar",
  finalizar: "Concluir",
  medidas: "Medidas",
  medidasApoio: "Todas opcionais. O app só guarda os números.",
  peso: "Peso (kg)",
  pressao: "Pressão",
  sistolica: "Máxima",
  diastolica: "Mínima",
  alturaUterina: "Altura uterina (cm)",
  alturaUterinaApoio: "A medida da barriga que o médico faz com a fita.",
  batimentos: "Batimentos do bebê (bpm)",
  confira: "Confira o valor",
  perguntas: "Perguntas",
  perguntasApoio: "Marque as que você fez. As outras seguem para a próxima.",
  feita: "Fiz",
  resposta: "Resposta (opcional)",
  orientacoes: "Orientações e retorno",
  orientacoesCampo: "Orientações (opcional)",
  retorno: "Retorno",
  sugestao: (dias: number, data: string) => `Retorno em ${dias} dias, por volta de ${data}.`,
  ritmo: "Ritmo comum no pré-natal. Seu médico pode orientar diferente.",
  marcarRetorno: "Marcar retorno",
  // Como foi
  comoFoi: "Como foi a consulta?",
  comoFoiApoio: "Conte o que aconteceu ou só marque como feita.",
  contar: "Contar como foi",
  foiCancelada: "Não aconteceu",
  dispensar: "Agora não",
  // Levar
  levar: "Levar para a consulta",
  levarApoio: "Um resumo para mostrar ao médico.",
  levarPerguntas: "Perguntas",
  levarRemedios: "Medicamentos em uso",
  levarExames: "Exames dos últimos 30 dias",
  levarMedidas: "Últimas medidas",
  levarNada: "Nada por aqui.",
  compartilhar: "Compartilhar",
  copiado: "Resumo copiado ✓",
  resumoTitulo: "Para a consulta (Ninho)",
  // Home
  homeTitulo: "Próxima consulta",
  verTodas: "Ver todas",
  adicionar: "Adicionar",
  nenhuma: "Nenhuma consulta marcada.",
} as const;
