/** Copy da funcionalidade 06 · Diário de grávida. */
export const diarioCopy = {
  titulo: "Diário",
  escrever: "+ Escrever",
  vazio: "Registre como foi descobrir a gravidez",
  vazioBotao: "Escrever agora",
  buscar: "Buscar no diário",
  buscarPlaceholder: "Buscar nas suas entradas",
  semResultado: "Nada encontrado nas suas entradas.",
  filtro: "Filtrar por marco",
  todos: "Tudo",
  marcos: "Marcos",
  verMarcos: "Ver todos os marcos",
  semana: (n: number) => `semana ${n}`,
  escritoPor: (nome: string) => `Escrito por ${nome}`,
  compartilhada: "compartilhada",
  comAudio: "com áudio",
  fotos: (n: number) => (n === 1 ? "1 foto" : `${n} fotos`),
  // Card de marco
  responder: "Responder",
  pular: "Pular",
  maisTarde: "Mais tarde",
  pulado: "Esse marco não volta mais.",
  adiado: "A gente lembra de novo em 3 dias.",
  // Editor
  nova: "Nova entrada",
  editar: "Editar entrada",
  campoTexto: "Como foi",
  placeholderLivre: "Escreva do seu jeito…",
  ditar: "Ditar",
  pararDitado: "Parar de ditar",
  ditadoFalhou: "O ditado não funcionou aqui. Gravando só o áudio.",
  audio: "Áudio",
  gravar: "Gravar áudio",
  pararGravacao: "Parar",
  gravando: (t: string) => `Gravando · ${t} de 3:00`,
  removerAudio: "Remover áudio",
  semMicrofone: "Sem acesso ao microfone. Libere nas configurações do navegador.",
  fotosRotulo: "Fotos (até 3)",
  adicionarFoto: "Adicionar foto",
  removerFoto: (n: number) => `Remover a foto ${n}`,
  data: "Data",
  dataFutura: "A data não pode ser no futuro.",
  vazia: "Escreva algo, grave um áudio ou junte uma foto.",
  salvar: "Salvar",
  salva: "Guardado no diário ✓",
  salvaSemAudio: "Guardado sem o áudio ✓",
  salvarSemAudio: "Salvar o texto sem o áudio",
  processandoFoto: "Preparando a foto…",
  // Entrada
  editarEntrada: "Editar",
  excluir: "Excluir",
  excluirTitulo: "Excluir esta entrada?",
  excluirTexto: "É definitivo: o texto, o áudio e as fotos somem.",
  excluida: "Entrada excluída",
  cancelar: "Cancelar",
  compartilhar: "Compartilhar com meu parceiro",
  compartilharApoio: "Ele vê só as entradas que você marcar.",
  compartilhado: "Seu parceiro já pode ler ✓",
  // Marcos
  estados: {
    respondido: "respondido",
    pulado: "pulado",
    adiado: "mais tarde",
    aberto: "aberto",
    em_breve: (s: number) => `a partir da semana ${s}`,
    passou: "a janela passou",
  },
  reabrir: "Responder mesmo assim",
} as const;
