/** Copy da funcionalidade 16 · Direitos da gestante. Frases curtas, sem juridiquês sem explicação. */
export const direitosCopy = {
  titulo: "Seus direitos",
  abas: { todos: "Todos", favoritos: "Favoritos" },
  busca: "Buscar direito",
  buscaPlaceholder: "Ex.: demissão, acompanhante, licença",
  resultados: (n: number) => (n === 1 ? "1 direito" : `${n} direitos`),
  nenhum: "Nada com esse texto. Tente outra palavra ou escolha um tema.",
  temas: { work: "Trabalho", health: "Saúde", birth: "Parto", postpartum: "Pós-parto", benefits: "Benefícios" },
  temaRotulo: "Tema",
  todosOsTemas: "Todos os temas",
  paraEstaFase: "Para esta fase",
  dispensar: (pergunta: string) => `Dispensar: ${pergunta}`,
  favoritosVazio: "Salve aqui os direitos que mais importam.",
  favoritosAtalhos: "Comece por estes:",
  verTodos: "Ver todos os direitos",
  ajuda: "Onde buscar ajuda",

  cartao: {
    detalhes: "Detalhes",
    baseLegal: "Base legal",
    seNaoRespeitarem: "Se não respeitarem",
    revisado: (data: string) => `Revisado em ${data}.`,
    rascunho: "Rascunho: aguarda revisão jurídica",
    rascunhoRodape: "Este cartão ainda não passou pela revisão de uma pessoa da área jurídica.",
    conferir: "Conferir atualização",
    conferirApoio: "A revisão deste cartão tem mais de um ano. A lei pode ter mudado.",
    atualizado: "Atualizado",
    atualizadoApoio: "Este cartão mudou depois que você o salvou.",
    favoritar: "Favoritar",
    desfavoritar: "Tirar dos favoritos",
    favoritado: "Nos seus favoritos ✓",
    compartilhar: "Compartilhar",
    copiado: "Texto copiado ✓",
    naoEncontrado: "Esse direito não está disponível agora.",
    abrirLei: (lei: string) => `Abrir ${lei} no site do Planalto`,
  },
  // RN-06: aviso fixo em todo cartão.
  aviso: "Informação geral, não é orientação jurídica. Em caso de dúvida, procure a Defensoria Pública, o sindicato ou um advogado.",

  canais: {
    titulo: "Onde buscar ajuda",
    apoio: "Ligações gratuitas e serviços públicos. Toque para ligar.",
    ligar: (nome: string, numero: string) => `Ligar para ${nome}, ${numero}`,
    site: "Abrir o site",
    vazio: "Os canais aparecem aqui assim que forem conferidos.",
    rascunho: "Números a conferir antes de publicar",
  },
} as const;
