/** Copy da aba Eu (mínimo desta versão; a spec 03 completa). */
export const euCopy = {
  titulo: "Eu",
  nome: "Nome",
  semNome: "Sem nome",
  dpp: "Data prevista do parto",
  nascimento: "Data de nascimento do bebê",
  tema: "Aparência",
  temas: { auto: "Automático", claro: "Claro", escuro: "Escuro" },
  consultas: "Consultas",
  bebe: "Bebê",
  familia: "Família",
  guardados: "Guardados",
  diario: "Diário de sintomas",
  diarioGravidez: "Diário da gravidez",
  medicamentos: "Medicamentos",
  exames: "Exames",
  parceiro: "Parceiro",
  calendario: "Calendário",
  faq: "Posso comer?",
  direitos: "Seus direitos",
  nomes: "Nomes do bebê",
  cartas: "Cartas para o bebê",
  artigos: "Artigos da gravidez",
  planoParto: "Plano de parto, malas e enxoval",
  avisos: "Avisos",
  novos: (n: number) => (n === 1 ? "1 novo" : `${n} novos`),
  galeria: "Exames e ultrassons guardados",
  barriga: "Foto da barriga",
  notificacoes: "Notificações",
  discreto: "Modo discreto",
  discretoApoio: "O aviso não mostra o nome do remédio.",
  suspensas: "Pausar todos os avisos",
  suspensasApoio: "Nada chega até você ligar de novo.",
  ativarAvisos: "Receber os avisos neste aparelho",
  avisosAtivos: "Avisos ligados neste aparelho ✓",
  avisosNegados: "O navegador bloqueou os avisos. Libere nas configurações.",
  conta: "Conta",
  anonima: "Só neste aparelho",
  recomecar: "Apagar tudo e recomeçar",
  recomecarConfirma: "Isso apaga seus dados deste aparelho. Digite \"apagar\" para confirmar.",
  confirmar: "Confirmar",
  cancelar: "Cancelar",
  placeholders: {
    bebe: "Depois do parto, tudo do bebê fica aqui.",
    registrarNascimento: "Registrar nascimento",
    enxoval: "O enxoval chega em breve.",
    meAvise: "Me avise",
    avisado: "A gente te avisa ✓",
  },
} as const;
