/** Copy da funcionalidade 03 · Lembrete para marcar exames. */
export const examesCopy = {
  titulo: "Meus exames",
  referencia: "Calendário de referência. Seu médico define quais exames você precisa e quando.",
  secoes: {
    agora: "Agora",
    proximos: "Próximos",
    marcados: "Marcados",
    feitos: "Feitos",
    anteriores: "Anteriores",
    dispensados: "Dispensados",
  },
  apoioSecao: {
    agora: "A janela está aberta ou abre logo. Hora de marcar.",
    anteriores: "A janela de referência já passou.",
  },
  janela: (inicio: string, fim: string) => `janela de ${inicio} a ${fim}`,
  semJanela: "sem janela definida",
  marcadoPara: (quando: string) => `marcado ${quando}`,
  diaTodo: "dia todo",
  feitoEm: (data: string) => `feito em ${data}`,
  feito: "feito",
  marcar: "Marcar",
  remarcar: "Remarcar",
  jaFiz: "Já fiz",
  concluir: "Concluir",
  dispensar: "O médico não pediu",
  restaurar: "Restaurar",
  apagar: "Apagar",
  adicionar: "Adicionar exame",
  outros: "Outros exames comuns",
  criarMeu: "Criar o meu",
  nomeMeu: "Nome do exame",
  nomeErro: "Escreva de 3 a 60 letras.",
  semanaInicio: "Da semana (opcional)",
  semanaFim: "Até a semana (opcional)",
  semanasErro: "Semanas de 4 a 42, a primeira antes da segunda.",
  criar: "Criar",
  criado: "Exame adicionado ✓",
  // Marcar
  sheetMarcar: "Marcar exame",
  data: "Data",
  hora: "Hora (opcional)",
  local: "Local (opcional)",
  observacao: "Observação (opcional)",
  salvar: "Salvar",
  erroSemData: "Escolha a data.",
  erroPassado: "Essa data já passou. Se você já fez, use \"Já fiz\".",
  foraDaJanela: "Essa data está fora da janela de referência. Tudo bem se foi o que o médico pediu.",
  marcado: "Exame marcado ✓",
  // Concluir
  sheetConcluir: "Exame feito",
  anexarPergunta: "Anexar resultado agora?",
  anexarApoio: "Foto ou PDF. Fica guardado aqui, junto do exame.",
  anexar: "Anexar resultado",
  soMarcar: "Só marcar como feito",
  anexando: "Guardando…",
  concluido: "Exame feito ✓",
  anexoErro: "Não deu para guardar esse arquivo. Tenta outra foto ou PDF?",
  resultado: "Resultado",
  verResultado: "Ver resultado",
  // Card e lembrete
  foiOntem: "Seu exame foi ontem?",
  foiEm: (nome: string, quando: string) => `${nome} · ${quando}`,
  remarquei: "Remarquei",
  dispensado: "Dispensado. Dá para restaurar em \"Dispensados\".",
  restaurado: "Exame de volta à lista ✓",
  paraQueServe: "Para que serve",
  estado: "Estado",
  estados: { to_schedule: "a marcar", scheduled: "marcado", done: "feito", dismissed: "dispensado" },
  vazio: "Quando a gestação estiver com a data, a lista aparece aqui.",
} as const;
