/** Copy da funcionalidade 09 · FAQ de comidas na gravidez. */
export const faqCopy = {
  titulo: "Posso comer?",
  busca: "Buscar alimento, bebida ou chá",
  buscaPlaceholder: "Ex.: açaí, sushi, café",
  categorias: "Categorias",
  categoria: {
    meat: "Carnes e ovos",
    fish: "Peixes e frutos do mar",
    dairy: "Leite e queijos",
    fruit_veg: "Frutas e verduras",
    drink: "Bebidas",
    sweet: "Doces",
    herb_tea: "Chás e ervas",
    other: "Outros",
  },
  maisBuscados: "Mais buscados",
  favoritos: "Meus favoritos",
  resultados: (n: number) => (n === 1 ? "1 resultado" : `${n} resultados`),
  naoAchei: "Não achei.",
  perguntar: "Perguntar",
  veredito: { safe: "Pode", caution: "Com cuidado", avoid: "Evite" },
  condicao: "Com uma condição",
  detalhes: "Detalhes",
  fonte: (f: string) => `Fonte: ${f}`,
  abrirFonte: "Abrir a fonte",
  revisado: (quem: string, quando: string) => `Revisado por ${quem} em ${quando}`,
  rascunho: "Rascunho: aguarda revisão profissional",
  perguntadoPor: (n: number) => (n === 1 ? "Perguntado por 1 mãe" : `Perguntado por ${n} mães`),
  aviso: "Informação geral. Em caso de dúvida, confirme com seu médico ou nutricionista.",
  favoritar: "Favoritar",
  desfavoritar: "Tirar dos favoritos",
  favoritado: "Nos seus favoritos ✓",
  naoEncontrado: "Este verbete não está disponível.",
  // Perguntar
  perguntarTitulo: "Perguntar",
  perguntarApoio: "Uma pessoa da equipe revisa e responde. Você recebe um aviso quando sair a resposta.",
  pergunta: "Sua pergunta",
  enviar: "Enviar pergunta",
  enviada: "Pergunta enviada ✓ A gente avisa quando responder.",
  jaPerguntaram: "Alguém já perguntou isso",
  tambemQuero: "Eu também quero saber",
  votado: "Anotado ✓ Você também vai receber a resposta.",
  jaVotou: "Você já está esperando esta resposta.",
  votos: (n: number) => (n === 1 ? "1 pessoa quer saber" : `${n} pessoas querem saber`),
  erros: {
    sem_rede: "Perguntar precisa de internet. A busca e os favoritos funcionam sem.",
    tamanho: "Escreva de 3 a 140 caracteres.",
    ofensa: "Essa pergunta tem palavras que a gente não aceita. Tenta reescrever?",
    limite_diario: "Você já mandou 5 perguntas hoje. Amanhã dá para mandar mais.",
    parecida: "Alguém já perguntou isso. Toque em \"Eu também quero saber\".",
    desconhecido: "Não deu certo agora. Tenta de novo?",
  },
  // Admin
  admin: {
    titulo: "FAQ de comidas",
    abertas: "Perguntas abertas",
    semAbertas: "Nenhuma pergunta aberta.",
    votos: (n: number) => `${n} ${n === 1 ? "voto" : "votos"}`,
    verbetes: "Verbetes",
    rascunhos: "Rascunhos",
    publicados: "Publicados",
    novo: "Novo verbete",
    editar: "Editar verbete",
    salvar: "Salvar rascunho",
    salvo: "Rascunho salvo ✓",
    publicar: "Publicar",
    publicado: "Publicado ✓",
    responde: "Responde a estas perguntas",
    revisor: "Revisado por (nome da pessoa)",
    revisadoEm: "Revisado em",
    precisaRevisao: "Para publicar: fonte, nome de quem revisou e data.",
    rejeitar: "Rejeitar",
    rejeitada: "Pergunta rejeitada",
    motivos: { fora_do_escopo: "Fora do escopo", pergunta_medica: "Pergunta médica", repetida: "Repetida" },
    campos: { slug: "Slug", name: "Nome", aliases: "Apelidos (separados por vírgula)", category: "Categoria", verdict: "Veredito", short_answer: "Resposta curta", details: "Detalhes", condition_note: "Condição", source_label: "Fonte", source_url: "Link da fonte" },
    iaRascunho: "A IA pode sugerir rascunho, mas nunca publica: a publicação é sempre de uma pessoa.",
    demo: "Sem servidor: o painel mostra a semente e não salva.",
    erro: "Não deu certo. Confira os campos e tente de novo.",
  },
} as const;
