/** Copy da funcionalidade 17 · Modo fé (católico). Frases curtas, tom "a gente". */
export const feCopy = {
  titulo: "Fé",
  biblioteca: "Biblioteca de fé",
  abas: { fixed: "Orações", intercessor: "Intercessores", blessing: "Bênção" },
  busca: "Buscar oração ou santo",
  buscaPlaceholder: "Ex.: parto, São José",
  resultados: (n: number) => (n === 1 ? "1 oração" : `${n} orações`),
  nenhum: "Nada com esse texto. Tente outra palavra.",
  daSemana: "Oração da semana",
  semana: (s: number) => `Semana ${s}`,
  favoritos: "Minhas favoritas",
  favoritar: "Favoritar",
  desfavoritar: "Tirar das favoritas",
  favoritado: "Nas suas favoritas ✓",
  compartilhar: "Compartilhar",
  copiado: "Texto copiado ✓",
  fonte: "Tamanho do texto",
  diminuir: "Diminuir o texto",
  aumentar: "Aumentar o texto",
  diaDoSanto: (dia: string) => `Festa em ${dia}`,
  origem: (fonte: string) => `Fonte: ${fonte}`,
  revisado: (quem: string, quando: string) => `Revisado por ${quem} em ${quando}.`,
  rascunho: "Rascunho: aguarda revisão",
  rascunhoRodape: "Este texto ainda não passou pela revisão de uma pessoa de formação católica.",
  // Spec 17, lista de lançamento: aviso fixo na bênção.
  avisoBencao: "Texto de oração. A bênção litúrgica é dada pelo sacerdote.",
  naoEncontrada: "Essa oração não está disponível agora.",
  vazio: "Ainda não tem oração publicada aqui. Volte em breve.",
  verbum: {
    titulo: "Leia o Evangelho do dia no Verbum",
    texto: "O Verbum é outro app, com a liturgia diária. Abre fora do Ninho, sem conta compartilhada.",
    abrir: "Abrir o Verbum",
  },
  desligado: {
    titulo: "O modo fé está desligado",
    texto: "Ligue em Eu para ver a oração da semana e a biblioteca. Seus favoritos ficam guardados.",
    ir: "Ir para Eu",
  },
  batismo: {
    titulo: "Batismo",
    apoio: "Uma lista para preparar o batismo, no seu tempo.",
    vazio: "A lista do batismo aparece depois que o nascimento é registrado.",
  },
  ajustes: {
    secao: "Fé",
    modo: "Modo fé",
    modoApoio: "Oração da semana, biblioteca de orações e marcos de fé no diário.",
    push: "Receber a oração da semana no push",
    pushApoio: "Vai junto com o aviso de que virou a semana.",
    biblioteca: "Biblioteca de fé",
    batismo: "Batismo",
  },
} as const;
