/** Copy da funcionalidade 01 · Galeria de exames e ultrassons. */
export const galeriaCopy = {
  titulo: "Exames e ultrassons",
  adicionar: "+ Adicionar",
  vazio: "Guarde aqui o primeiro ultrassom",
  vazioBotao: "Adicionar documento",
  tipos: {
    us_obstetric: "Ultrassom obstétrico",
    us_nuchal: "Translucência nucal",
    us_morpho: "Morfológico",
    us_other: "Outro ultrassom",
    blood: "Exame de sangue",
    urine: "Urina",
    glucose: "Glicemia",
    serology: "Sorologias",
    culture_gbs: "Estreptococo B",
    other: "Outro",
  },
  filtros: { todos: "Tudo", us: "Ultrassons" },
  filtro: "Filtrar por tipo",
  vista: "Ver como",
  grade: "Grade",
  linhaDoTempo: "Linha do tempo",
  semana: (n: number) => `semana ${n}`,
  paginas: (n: number) => (n === 1 ? "1 página" : `${n} páginas`),
  aguardando: "Aguardando envio",
  favorito: "favorito",
  exportar: "Exportar PDF",
  // Adicionar
  novo: "Novo documento",
  editar: "Editar documento",
  camera: "Câmera",
  galeria: "Galeria",
  pdf: "PDF",
  maisUmaPagina: "Mais uma página",
  origemApoio: "Fotografe cada página do laudo, escolha da galeria ou anexe o PDF.",
  preparando: "Preparando as páginas…",
  removerPagina: (n: number) => `Remover a página ${n}`,
  moverAntes: (n: number) => `Passar a página ${n} para antes`,
  tipo: "Tipo",
  tipoErro: "Escolha o tipo.",
  data: "Data do exame",
  dataErro: "Escolha a data.",
  dataFutura: "A data não pode ser no futuro.",
  dataAntigaTitulo: "Essa data é bem antes da gestação",
  dataAntigaTexto: "É mais de 90 dias antes da última menstruação. Quer guardar assim mesmo?",
  dataAntigaSim: "Guardar assim",
  titulo_: "Título (opcional)",
  observacao: "Observação (opcional)",
  semPaginas: "Junte ao menos uma página.",
  muitasPaginas: "Cada documento tem até 20 páginas.",
  grandeDemais: "Esse arquivo passou de 15 MB. Tenta uma foto menor?",
  ilegivel: "Não deu para abrir esse arquivo. Tenta outra foto ou PDF?",
  salvar: "Salvar",
  salvo: "Guardado na galeria ✓",
  cancelar: "Cancelar",
  // RN-04
  vincularTitulo: (exame: string) => `Este é o resultado de ${exame}?`,
  vincularTexto: "Se for, o exame fica como feito, com este documento.",
  vincularSim: "Sim, é ele",
  vincularNao: "Não",
  vinculado: (exame: string) => `${exame} marcado como feito ✓`,
  doExame: (exame: string) => `Resultado de ${exame}`,
  // Documento
  pagina: (i: number, n: number) => `Página ${i} de ${n}`,
  anterior: "Página anterior",
  proxima: "Próxima página",
  ampliar: "Ampliar",
  reduzir: "Reduzir",
  favoritar: "Favoritar",
  desfavoritar: "Tirar dos favoritos",
  compartilhar: "Compartilhar com meu parceiro",
  compartilharApoio: "Ele vê só os documentos que você marcar.",
  editarDoc: "Editar",
  excluir: "Excluir",
  excluirTitulo: "Excluir este documento?",
  excluirTexto: "É definitivo: as páginas somem deste aparelho e do armazenamento.",
  excluido: "Documento excluído",
  semArquivo: "Esta página ainda não chegou neste aparelho.",
  // IA
  lerLaudo: "Ler laudo",
  lendo: "Lendo o laudo…",
  resumo: "O que está escrito",
  avisoIa: "Transcrição automática. Confira com o documento original e converse com seu médico.",
  marcadoNoLaudo: "marcado no laudo",
  referencia: (r: string) => `referência: ${r}`,
  falhouIa: "Não consegui ler este laudo. O arquivo continua salvo.",
  semCota: (quando: string) => `As 20 leituras deste mês acabaram. Renova em ${quando}.`,
  semRedeIa: "A leitura do laudo precisa de internet.",
  aguardandoIa: "As páginas ainda estão subindo. Tenta de novo daqui a pouco.",
  semConsentimentoIa: "A permissão de leitura por IA está desligada.",
  restantes: (n: number) => (n === 1 ? "Resta 1 leitura este mês." : `Restam ${n} leituras este mês.`),
  laboratorio: (l: string) => `Laboratório: ${l}`,
  // Consentimento (texto final: revisão jurídica, decisão em aberto)
  consentimentoTitulo: "Ler o laudo com IA",
  consentimentoTexto: [
    "Para ler o laudo, as imagens deste documento são enviadas a um provedor de inteligência artificial que extrai o texto.",
    "A IA só transcreve o que está escrito. Ela não interpreta nem diz se um valor está alto ou baixo.",
    "Só acontece quando você toca em \"Ler laudo\". Você pode retirar a permissão em Eu a qualquer momento.",
  ],
  consentir: "Concordo, ler o laudo",
  naoConsentir: "Agora não",
  // Exportar
  exportarTitulo: "Exportar PDF",
  exportarApoio: "Escolha os documentos. Até 50 páginas.",
  selecionar: (t: string) => `Selecionar ${t}`,
  selecionadas: (p: number) => `${p} de 50 páginas`,
  passouExportacao: "Passou de 50 páginas. Tire algum documento.",
  gerar: "Gerar PDF",
  gerando: "Montando o PDF…",
  gerado: "PDF pronto ✓",
  link: "Baixar o PDF",
  linkApoio: "O link vale por 24 horas.",
  erroExportar: "Não deu para montar o PDF. Tenta de novo?",
  capaTitulo: "Exames e ultrassons",
  capaNome: (n: string) => `Nome: ${n}`,
  capaDpp: (d: string) => `Data prevista do parto: ${d}`,
  capaSemana: (s: number) => `Semana da gestação: ${s}`,
  capaGerado: (d: string) => `Gerado em ${d} pelo Ninho`,
  // Eu
  retirarIa: "Leitura de laudo por IA",
  retirarIaApoio: "Com a permissão ligada, as imagens vão ao provedor só quando você toca em \"Ler laudo\".",
} as const;
