/** Copy da funcionalidade 02 · Medicamentos. */
export const medicamentosCopy = {
  titulo: "Medicamentos",
  hoje: "Hoje",
  ontem: "Ontem",
  vazio: "Cadastre o primeiro lembrete",
  vazioApoio: "A gente lembra na hora e guarda o que você tomou, para mostrar no pré-natal.",
  cadastrar: "Cadastrar medicamento",
  meus: "Meus medicamentos",
  adesao: "Adesão",
  compartilhar: "Compartilhar lista",
  listaTitulo: "Meus medicamentos (Ninho)",
  listaCopiada: "Lista copiada ✓",
  semDoses: "Nenhuma dose programada neste dia.",
  seNecessario: "Se necessário",
  tomeiAgora: "Tomei agora",
  tomei: "Tomei",
  pular: "Pular",
  adiar: "Adiar 15 min",
  adiada: (hora: string) => `Adiada para ${hora}`,
  estados: {
    pending: (hora: string) => `às ${hora}`,
    taken: (hora: string) => `tomei às ${hora}`,
    skipped: "pulei",
    missed: "Sem registro",
  },
  registrada: "Dose registrada ✓",
  pulada: "Dose pulada",
  desfazer: "Desfazer",
  // Sheet de confirmação
  sheetTitulo: "Registrar dose",
  horarioReal: "Horário real",
  horarioFuturo: "Esse horário ainda não chegou.",
  // Lista
  ativos: "Ativos",
  arquivados: "Arquivados",
  adicionar: "Adicionar",
  lembreteDesligado: "lembrete desligado",
  // Cadastro
  novo: "Novo medicamento",
  editar: "Editar medicamento",
  aviso: "Anote exatamente o que seu médico receitou. O app só lembra e registra.",
  nome: "Nome",
  nomeErro: "Escreva o nome do medicamento.",
  dose: "Dose (opcional)",
  dosePlaceholder: "como está na receita",
  orientacao: "Orientação (opcional)",
  orientacaoPlaceholder: "ex.: em jejum, depois do almoço",
  frequencia: "Quando tomar",
  tipos: {
    fixed_times: "Horários fixos",
    interval: "A cada N horas",
    weekdays: "Dias da semana",
    as_needed: "Se necessário",
  },
  horarios: "Horários",
  adicionarHorario: "Mais um horário",
  removerHorario: (h: string) => `Remover ${h}`,
  horariosErro: "Escolha de 1 a 4 horários.",
  aCada: "A cada",
  horas: (n: number) => `${n} horas`,
  primeiraDose: "Primeira dose do dia",
  dias: "Dias",
  diasErro: "Escolha ao menos um dia.",
  inicio: "Começa em",
  fim: "Termina em (opcional)",
  fimErro: "O fim vem depois do começo.",
  lembrete: "Lembrete",
  lembreteApoio: "Desligado, você ainda registra as doses aqui.",
  semLembreteNecessario: "\"Se necessário\" não tem lembrete: registre quando tomar.",
  salvar: "Salvar",
  salvo: "Medicamento salvo ✓",
  arquivar: "Arquivar",
  arquivado: "Arquivado. O histórico fica.",
  reativar: "Reativar",
  apagar: "Apagar",
  apagarConfirma: "Apagar este medicamento? As doses já registradas continuam na adesão.",
  apagado: "Medicamento apagado",
  cancelar: "Cancelar",
  diasSemana: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
  diasSemanaLongo: ["domingo", "segunda", "terça", "quarta", "quinta", "sexta", "sábado"],
  // Adesão
  ultimos7: "Últimos 7 dias",
  ultimos30: "Últimos 30 dias",
  semDados: "Ainda sem doses registradas.",
  sequencia: (n: number) => (n === 1 ? "1 dia seguido com tudo tomado" : `${n} dias seguidos com tudo tomado`),
  sequenciaZero: "A sequência começa no primeiro dia com todas as doses tomadas.",
  legendaAdesao: (t: number, p: number, s: number) => `${t} tomadas · ${p} puladas · ${s} sem registro`,
  // Voz
  vozQual: "Qual você tomou?",
  vozRegistrada: (nome: string) => `${nome}: dose registrada ✓`,
  vozNaoAchei: "Não achei esse remédio na sua lista.",
} as const;
