/** Copy da funcionalidade 15 · Lista de nomes. Frases curtas, tom "a gente". */
export const nomesCopy = {
  titulo: "Nomes",
  descobrir: "Descobrir",
  comece: "Comece a descobrir nomes",
  comeceApoio: "Deslize para a direita para curtir e para a esquerda para descartar. Ou use os botões.",
  progresso: (n: number, total: number) => `${n} de ${total}`,
  curtir: "Curtir",
  descartar: "Descartar",
  desfazer: "Desfazer",
  abrirDetalhe: (nome: string) => `Ver detalhes de ${nome}`,
  sessaoFim: "Você viu os 20 desta rodada.",
  maisVinte: "Mais 20 nomes",
  acabou: "Você viu todos os nomes destes filtros.",
  limparFiltros: "Limpar filtros",
  filtros: "Filtros",
  aplicar: "Ver nomes",
  sexo: { rotulo: "Para", f: "Menina", m: "Menino", todos: "Tanto faz" },
  letra: "Começa com",
  letraTodas: "Qualquer letra",
  silabas: { rotulo: "Sílabas", todas: "Qualquer", n: (n: number) => (n >= 4 ? "4 ou mais" : String(n)) },
  origem: { rotulo: "Origem", todas: "Qualquer" },
  popularidade: { rotulo: "Popularidade", todas: "Qualquer", muito_comum: "Muito comum", comum: "Comum", raro: "Raro" },
  significadoEmBreve: "Significado em breve",
  rascunho: "Significado a revisar",
  origemDe: (o: string) => `Origem ${o}`,
  santo: (nome: string, dia: string | null) => (dia ? `${nome} · festa em ${dia}` : nome),

  meus: {
    titulo: "Meus nomes",
    abas: { curtidos: "Curtidos", descartados: "Descartados", match: "Match" },
    top: "Seu top 10",
    topApoio: "Só você vê. Use as setas para mudar a ordem.",
    outros: "Outros curtidos",
    subir: (nome: string) => `Subir ${nome}`,
    descer: (nome: string) => `Descer ${nome}`,
    porNoTop: "Pôr no top 10",
    tirarDoTop: (nome: string) => `Tirar ${nome} do top 10`,
    topCheio: "O top 10 está cheio",
    recuperar: "Recuperar",
    curtidosVazio: "Os nomes que você curtir aparecem aqui.",
    descartadosVazio: "Nada descartado.",
    matchVazio: "Quando vocês dois curtirem o mesmo nome, ele aparece aqui.",
    matchSemParceiro: "Convide o parceiro em Eu → Parceiro para votarem juntos. Só o que os dois curtirem aparece aqui.",
    adicionar: "Adicionar um nome",
  },

  adicionar: {
    titulo: "Adicionar nome",
    campo: "Nome",
    placeholder: "Ex.: Joaquim",
    apoio: "Só letras, espaço e hífen. Ele entra como curtido.",
    salvar: "Adicionar",
    invalido: "Use só letras, espaço e hífen, até 40 caracteres.",
    adicionado: (nome: string) => `${nome} entrou nos curtidos ✓`,
  },

  detalhe: {
    ouvir: "Ouvir",
    sobrenomes: "Com sobrenome",
    sobrenome: (n: number) => `Sobrenome ${n}`,
    sobrenomeApoio: "Só para ver como fica. Não guardamos.",
    iniciais: "Iniciais",
    silabas: (n: number) => (n === 1 ? "1 sílaba" : `${n} sílabas`),
    naoEncontrado: "Esse nome não está disponível.",
  },

  escolher: {
    botao: "Este é o nome!",
    titulo: (nome: string) => `${nome} é o nome?`,
    texto: "O nome passa a aparecer no app para vocês dois. Dá para desfazer em Eu.",
    confirmar: "Sim, é este",
    cancelar: "Ainda não",
    pronto: (nome: string) => `${nome} ✓`,
    semRede: "Escolher o nome precisa de internet.",
    semMatch: "Esse nome ainda não deu match.",
    erro: "Não deu certo. Tente de novo.",
  },

  match: {
    titulo: "Deu match!",
    texto: (nome: string) => `Vocês dois curtiram ${nome}.`,
    ver: "Ver os matches",
    fechar: "Fechar",
  },

  ajustes: {
    escolhido: (nome: string) => `Nome escolhido: ${nome}`,
    desfazer: "Desfazer a escolha",
    desfeito: "Escolha desfeita",
  },
  esperando: (nome: string) => `Esperando ${nome}`,
} as const;
