/** Copy da funcionalidade 12 · Modo parceiro. */
export const parceiroCopy = {
  // Gestante > Parceiro
  titulo: "Parceiro",
  apoio: "Convide quem vai acompanhar a gravidez com você. Você escolhe o que essa pessoa vê.",
  convidar: "Convidar meu parceiro",
  gerando: "Gerando o convite…",
  link: "Link do convite",
  codigo: "Ou o código",
  codigoApoio: "Dá para digitar o código em ninho.app/convite.",
  validade: (quando: string) => `Vale até ${quando}. Depois disso, é só gerar outro.`,
  copiarLink: "Copiar link",
  copiado: "Link copiado ✓",
  compartilhar: "Enviar convite",
  gerarOutro: "Gerar outro convite",
  gerarOutroApoio: "O convite anterior deixa de valer.",
  estado: {
    valido: "Convite enviado, esperando aceitar",
    expirado: "O convite expirou",
    revogado: "Convite cancelado",
    usado: "Convite aceito",
    inexistente: "",
  },
  semConvite: "Nenhum convite ativo.",
  jaTemParceiro: "Já tem um parceiro acompanhando. Para convidar outra pessoa, remova o atual.",
  permissoesTitulo: "O que ele vê",
  permissoes: {
    agenda: "Agenda",
    agendaApoio: "Consultas, pauta e exames marcados (só nome e data).",
    fotos: "Fotos da barriga",
    fotosApoio: "A grade semana a semana.",
    plano: "Plano de parto e listas",
    planoApoio: "Ler o plano e marcar itens da mala e do enxoval.",
  },
  sempreFora: "Medicamentos, medidas das consultas e exames feitos ficam só com você.",
  salvo: "Permissão atualizada ✓",
  remover: "Remover parceiro",
  removerTitulo: "Remover o parceiro?",
  removerTexto: "Ele perde o acesso na hora. O que ele escreveu no diário continua com você.",
  removido: "Parceiro removido",
  erro: "Não deu certo agora. Tenta de novo?",
  precisaServidor: "Convite só funciona neste aparelho enquanto o app não está conectado.",

  // Aceitar convite (tela 2)
  aceitarTitulo: (quem: string) => `${quem} te convidou para acompanhar a gravidez`,
  oQueVe: "O que você vai ver",
  veLista: ["A semana, o tamanho do bebê e a data provável", "Como ajudar a cada semana", "Consultas e exames marcados, se ela liberar", "O plano de parto e as listas, se ela liberar"],
  naoVe: "Medicamentos, medidas das consultas e exames dela continuam só com ela.",
  seuNome: "Seu nome",
  entrarParaAceitar: "Para aceitar, entre com uma conta. Assim você não perde o acesso se trocar de celular.",
  comGoogle: "Continuar com Google",
  comEmail: "Continuar com e-mail",
  email: "Seu e-mail",
  enviarLink: "Enviar link de acesso",
  linkEnviado: "Enviamos um link para o seu e-mail. Abra por ele para continuar.",
  aceitar: "Aceitar e acompanhar",
  aceitando: "Entrando…",
  aceito: "Pronto! Agora você acompanha a gravidez ✓",
  digiteCodigo: "Digite o código do convite",
  codigoRotulo: "Código de 6 letras e números",
  continuar: "Continuar",
  erros: {
    expirado: "Convite expirado. Peça um novo convite para ela.",
    revogado: "Este convite foi cancelado. Peça um novo convite para ela.",
    usado: "Este convite já foi usado. Peça um novo convite para ela.",
    inexistente: "Não achamos este convite. Confira o link ou o código.",
    outra_conta: "Esta conta já acompanha outra gestação. Use outra conta para acompanhar.",
    ja_tem_parceiro: "Esta gestação já tem um parceiro acompanhando.",
    ja_e_membro: "Você já acompanha esta gestação.",
    precisa_login: "Entre com uma conta para aceitar.",
    desconhecido: "Não deu certo agora. Tenta de novo?",
  },

  // Home do parceiro (tela 3)
  semanaTitulo: (s: number) => `Semana ${s}`,
  tamanho: (t: string) => `O bebê está do tamanho de ${t}`,
  dpp: (d: string) => `Data provável: ${d}`,
  // As frases da semente já começam com "Ela pode estar…".
  sentindoTitulo: "Como ela pode estar",
  ajudarTitulo: "Como ajudar esta semana",
  compromissosTitulo: "Próximos compromissos",
  semCompromissos: "Ela ainda não adicionou compromissos.",
  consulta: "Consulta",
  atalhos: "Atalhos",
  calendario: "Calendário",
  pauta: "Pauta da consulta",
  listas: "Plano de parto e listas",
  diario: "Diário",
  semDpp: "Assim que ela registrar a data provável, a semana aparece aqui.",

  // Ajustes do parceiro (tela 4)
  avisosTitulo: "Meus avisos",
  avisos: {
    vespera: "Véspera de consulta",
    vesperaApoio: "Às 18h do dia anterior.",
    exame: "Exame marcado",
    exameApoio: "Quando ela marcar um exame.",
    marcos: "Marcos da gravidez",
    marcosApoio: "Semanas 12, 20, 28, 36, 38 e 40.",
  },
  avisosLimite: "No máximo 3 avisos por semana.",
  sair: "Sair da gestação",
  sairTitulo: "Sair da gestação?",
  sairTexto: "Você deixa de ver a gravidez. O que escreveu no diário continua com ela.",
  saiu: "Você saiu da gestação",

  // Central de avisos
  cancelar: "Cancelar",
  centralTitulo: "Avisos",
  centralVazia: "Nenhum aviso por aqui.",
} as const;
