/** Copy da funcionalidade 10 · Plano de parto, malas e enxoval. */
export const planoCopy = {
  titulo: "Plano de parto",
  progresso: (n: number) => `${n} de 5 etapas`,
  etapas: {
    onde: { titulo: "Onde", apoio: "Maternidade, cobertura e equipe" },
    como: { titulo: "Como", apoio: "O que você deseja para o parto" },
    quem: { titulo: "Quem", apoio: "Acompanhante, doula e emergência" },
    documentos: { titulo: "Documentos", apoio: "O que levar para a maternidade" },
    malas: { titulo: "Malas e enxoval", apoio: "Para você, o bebê e quem vai junto" },
  },
  concluida: "concluída",
  concluir: "Concluir etapa",
  etapaConcluida: "Etapa concluída ✓",
  gerarPdf: "Gerar PDF",
  ligar: "Ligar para a maternidade",
  salvando: "Salvando…",
  salvoAuto: "Salvo",
  somenteLeitura: "Só ela edita esta parte. Você pode marcar e adicionar itens das listas.",
  // Onde
  maternidade: "Maternidade",
  endereco: "Endereço",
  telefone: "Telefone da maternidade",
  mapa: "Link do mapa (opcional)",
  abrirMapa: "Abrir no mapa",
  cobertura: "Cobertura",
  coberturas: { sus: "SUS", private: "Plano de saúde", unknown: "Ainda não sei" },
  convenio: "Nome do plano",
  medico: "Médico(a)",
  telMedico: "Telefone do médico(a)",
  direitoConhecer: "Você tem direito de conhecer e se vincular à maternidade onde vai ter o bebê, pelo SUS (Lei 11.634/2007).",
  // Como
  comoAviso: "Preferências, não garantias. O que acontece no parto depende da sua saúde, da do bebê e da equipe. Converse com seu médico.",
  partoDesejado: "Tipo de parto desejado",
  partos: { vaginal: "Normal", cesarean: "Cesárea", open: "Aberta às duas", undecided: "Ainda decidindo" },
  analgesia: "Analgesia",
  analgesias: { none: "Sem", epidural: "Com peridural", open: "Aberta", undecided: "Ainda decidindo" },
  prefs: {
    skin_to_skin: "Contato pele a pele logo após o nascimento",
    delayed_cord_clamping: "Clampeamento tardio do cordão",
    breastfeeding_first_hour: "Amamentar na primeira hora",
    companion_in_room: "Acompanhante na sala o tempo todo",
    calm_environment: "Ambiente calmo, luz baixa",
    free_movement: "Liberdade para se movimentar",
  },
  prefsApoio: {
    delayed_cord_clamping: "Esperar um pouco antes de cortar o cordão.",
  } as Record<string, string>,
  fotos: "Fotos e vídeo",
  fotosOpcoes: { allowed: "Pode", no: "Prefiro que não" },
  observacoes: "Observações",
  // Quem
  direitoAcompanhante: "A lei garante a presença de um acompanhante de sua escolha no trabalho de parto, parto e pós-parto imediato (Lei 11.108/2005).",
  acompanhante: "Acompanhante",
  doula: "Doula",
  emergencia: "Contato de emergência",
  nome: "Nome",
  tel: "Telefone",
  // Listas
  listas: {
    documents: "Documentos",
    bag_mother: "Mala da mãe",
    bag_baby: "Mala do bebê",
    bag_companion: "Mala do acompanhante",
    layette: "Enxoval",
    baptism: "Batizado",
  },
  progressoLista: (f: number, t: number) => `${f} de ${t}`,
  adicionarItem: "Adicionar item",
  novoItem: (lista: string) => `Novo item em ${lista}`,
  itemAdicionado: "Item adicionado ✓",
  quantidade: (t: string) => `Quantidade de ${t}`,
  menos: (t: string) => `Uma a menos de ${t}`,
  mais: (t: string) => `Uma a mais de ${t}`,
  remover: (t: string) => `Remover ${t}`,
  renomear: (t: string) => `Renomear ${t}`,
  marcar: (t: string) => `Marcar ${t}`,
  // Anexos
  anexar: (t: string) => `Anexar foto de ${t}`,
  anexo: (t: string, n: number) => `Foto ${n} de ${t}`,
  removerAnexo: (n: number) => `Remover a foto ${n}`,
  itemCheio: "Até 3 fotos por documento.",
  anexoErro: "Não deu para abrir essa foto. Tenta outra?",
  // PDF
  pdfTitulo: "Plano de parto",
  pdfPrevia: "Prévia do PDF",
  pdfApoio: "Uma página com maternidade, equipe, acompanhantes e preferências. Funciona sem internet.",
  pdfVazio: "O PDF sai com o que estiver preenchido. Seções vazias ficam de fora.",
  compartilhar: "Compartilhar PDF",
  baixar: "Baixar PDF",
  gerando: "Montando o PDF…",
  pronto: "PDF pronto ✓",
  rodape: "feito com Ninho",
  pdfData: (d: string) => `Gerado em ${d}`,
  pdfNome: (n: string) => `Nome: ${n}`,
  // Home
  qualMaternidade: "Qual maternidade?",
  qualMaternidadeApoio: "Deixe o endereço e o telefone à mão para a hora H.",
  qualMaternidadeAcao: "Preencher agora",
  erro: "Não deu certo agora. Tenta de novo?",
} as const;
