/** Copy da funcionalidade 07 · Retrospectiva. Os textos dos slides também moram aqui (o renderizador só desenha). */
export const retroCopy = {
  titulo: "Retrospectiva",
  memorias: "Memórias",
  memoriasApoio: "Sua gravidez contada em uma história para guardar.",
  memoriasVazio: "A retrospectiva aparece a partir da semana 36.",
  quantos: (n: number) => (n === 1 ? "1 slide" : `${n} slides`),
  previa: "Prévia",
  final: "Retrospectiva final",
  card: {
    previa: "Sua história até aqui",
    previaApoio: "Fotos, marcos e números da gravidez, em uma história.",
    final: "Sua retrospectiva está pronta",
    finalApoio: "A gravidez inteira, do positivo ao nascimento.",
    abrir: "Assistir",
  },

  slides: {
    rotulo: { preview: "Prévia", final: "Retrospectiva" },
    capa: "A história de",
    vocesNome: "vocês",
    bebeNome: "o bebê",
    duracaoRotulo: "Tempo juntos",
    semanas: (n: number) => (n === 1 ? "semana" : "semanas"),
    eDias: (d: number) => (d === 0 ? "certinhas" : d === 1 ? "e 1 dia" : `e ${d} dias`),
    duracaoFinal: "da primeira menstruação ao nascimento",
    duracaoPrevia: "e contando",
    discovery: "Quando descobri",
    first_kick: "O primeiro chute",
    sexo: "Quando soubemos",
    nome: "O nome",
    quote: "Do meu diário",
    partner: "Do diário de quem esteve junto",
    barriga: "Você crescendo junto",
    barrigaSemanas: (a: number, b: number) => `Da semana ${a} à ${b}`,
    semana: (n: number) => `Semana ${n}`,
    ultrassom: "Um retrato antes de tudo",
    numeros: "Em números",
    consultas: (n: number) => (n === 1 ? "consulta feita" : "consultas feitas"),
    documentos: (n: number) => (n === 1 ? "documento guardado" : "documentos guardados"),
    fotos: (n: number) => (n === 1 ? "foto da barriga" : "fotos da barriga"),
    entradas: (n: number) => (n === 1 ? "página no diário" : "páginas no diário"),
    eEntao: "E então",
    chegou: (nome: string) => `${nome} chegou`,
    ateLogo: "Até logo,",
    ateLogoApoio: "A gente se vê do outro lado.",
    hora: (h: string) => h.replace(":", "h"),
    ponteTitulo: "Agora começa outra história",
    ponte: (nome: string) => `Começar o diário de ${nome}`,
    marca: "Ninho",
  },

  player: {
    rotulo: "Retrospectiva em stories",
    fechar: "Fechar",
    anterior: "Slide anterior",
    proximo: "Próximo slide",
    pausar: "Pausar",
    continuar: "Continuar",
    slide: (i: number, n: number) => `Slide ${i} de ${n}`,
    carregando: "Montando a sua história…",
    editar: "Editar",
    exportar: "Exportar",
    ponte: "Abrir a home do bebê",
    fim: "Fim da história.",
    indisponivel: "A retrospectiva aparece a partir da semana 36. Depois do nascimento, chega a versão final.",
    soGestante: "A retrospectiva é de quem gestou. Ela pode compartilhar o vídeo com você.",
    voltar: "Voltar para Memórias",
  },

  editor: {
    titulo: "Editar a retrospectiva",
    apoio: "Escolha o que entra. Os slides essenciais ficam sempre.",
    ocultar: "Mostrar na retrospectiva",
    obrigatorio: "Sempre aparece",
    trocarFrase: "Trocar frase",
    nomes: {
      cover: "Capa",
      duration: "Duração",
      discovery: "Quando descobri",
      belly: "Fotos da barriga",
      ultrasound: "Ultrassom favorito",
      first_kick: "Primeiro chute",
      sex_name: "Sexo e nome",
      numbers: "Em números",
      quote: "Uma frase do diário",
      partner: "Uma frase do parceiro",
      closing: "Encerramento",
      bridge: "Diário do bebê",
    } as Record<string, string>,
    escolherFrase: "Escolher uma frase",
    fraseTitulo: (slide: string) => `Frase: ${slide}`,
    minhas: "Do meu diário",
    doParceiro: "Do parceiro",
    digitar: "Ou escreva a frase",
    digitarRotulo: "Sua frase",
    usarTexto: "Usar esta frase",
    remover: "Tirar a frase",
    padrao: "Voltar ao padrão",
    semEntradas: "Ainda não há entradas no diário.",
    adicionar: "Adicionar à retrospectiva",
  },

  exportar: {
    titulo: "Exportar",
    exportarBotao: "Exportar",
    manterAberta: "Mantenha esta tela aberta.",
    video: "Vídeo vertical",
    videoApoio: (s: number) => `${s} segundos, 1080 × 1920.`,
    imagens: "Imagens dos slides",
    imagensApoio: "Um PNG por slide, 1080 × 1920.",
    marca: "No grátis, sai com a marca Ninho.",
    baixando: (a: number, b: number) => `Baixando fotos ${a} de ${b}`,
    gravando: (s: number) => `Gravando o vídeo… ${s}s`,
    gerando: "Gerando as imagens…",
    semRede: "Conecte-se para baixar as fotos.",
    semVideo: "Este navegador não grava vídeo. As imagens funcionam.",
    pronto: "Pronto ✓",
    erro: "Não deu certo. Tente de novo.",
    nomeVideo: "retrospectiva-ninho",
  },

  nascimento: {
    peso: "Peso (g, opcional)",
    comprimento: "Comprimento (cm, opcional)",
    erroPeso: "Peso entre 500 e 7.000 g.",
    erroComprimento: "Comprimento entre 20 e 65 cm.",
    erroCedo: "Essa data é cedo demais para a gestação registrada.",
  },
} as const;
